# SPDX-FileCopyrightText: 2026 Stefano Campanella
# SPDX-License-Identifier: MIT
# ==== UNPACK PARAMETERS ====
time_dim = "time"

# ==== READING CONFIGURATION ====
[read]
engine = "zarr"
inline_array = false
chunks = {time = "auto", depth = 1, lat = -1, lon = -1}

[[postprocess]]
name = "chunk"
time = 1
depth = 1
lat = -1
lon = -1


# ==== SAVING CONFIGURATION ====
[save]
consolidated = true
chunks = {time =1, depth = 1, lat = -1, lon = -1}
compressor = {cname = "lz4", clevel = 1}

