start = 1999-01-01T00:00:00
end = 2021-06-01T00:00:00

[datasets.era5.checkpointing]
step = '16D'
compressor = {cname = 'lz4', clevel = 3}

[[datasets.era5.parts]]
filename_or_obj = 'gs://gcp-public-data-arco-era5/ar/full_37-1h-0p25deg-chunk-1.zarr-v3'
engine = 'zarr'
consolidated = true
storage_options = {token = "anon"}
chunks = {time = 24, latitude = -1, longitude = -1}

[[datasets.era5.postprocess]]
name = 'select_variables'
variables = [
    '10m_u_component_of_wind',
    '10m_v_component_of_wind',
    '2m_dewpoint_temperature',
    '2m_temperature',
    'geopotential_at_surface',
    'land_sea_mask',
    'mean_sea_level_pressure']

[[datasets.era5.postprocess]]
name = 'flip'
dim = 'latitude'

[[datasets.era5.postprocess]]
name = 'regrid'
method = 'cubic'
latitude_dim = 'latitude'
longitude_dim = 'longitude'
grid = {south = 30.00, north = 46.00, west = -5.60, east = 36.40, resolution_lat = 0.04, resolution_lon = 0.04}

[[datasets.era5.postprocess]]
name = 'resample'
time = '1 D'
label = 'left'
closed = 'left'
reduce = 'mean'

[[datasets.era5.postprocess]]
name = 'rename'

[datasets.era5.postprocess.name_dict]
10m_u_component_of_wind = '10u'
10m_v_component_of_wind = '10v'
2m_dewpoint_temperature = '2d'
2m_temperature = '2t'
geopotential_at_surface = 'z'
land_sea_mask = 'lsm'
mean_sea_level_pressure = 'msl'

[[datasets.era5.postprocess]]
name = 'rename_coordinates'
name_dict = {latitude = 'lat', longitude = 'lon'}

[datasets.era5_cumulative.checkpointing]
step = '16D'
compressor = {cname = 'lz4', clevel = 3}

[[datasets.era5_cumulative.parts]]
filename_or_obj = 'gs://gcp-public-data-arco-era5/ar/full_37-1h-0p25deg-chunk-1.zarr-v3'
engine = 'zarr'
consolidated = true
storage_options = {token = "anon"}
chunks = {time = 24, latitude = -1, longitude = -1}

[[datasets.era5_cumulative.postprocess]]
name = 'select_variables'
variables = [
    'surface_solar_radiation_downwards',
    'surface_thermal_radiation_downwards',
    'total_precipitation']

[[datasets.era5_cumulative.postprocess]]
name = 'flip'
dim = 'latitude'

[[datasets.era5_cumulative.postprocess]]
name = 'regrid'
method = 'cubic'
latitude_dim = 'latitude'
longitude_dim = 'longitude'
grid = {south = 30.00, north = 46.00, west = -5.60, east = 36.40, resolution_lat = 0.04, resolution_lon = 0.04}

[[datasets.era5_cumulative.postprocess]]
name = 'clip_negative'
variables = ['total_precipitation']

[[datasets.era5_cumulative.postprocess]]
name = 'resample'
time = '1 D'
label = 'left'
closed = 'left'
reduce = 'sum'

[[datasets.era5_cumulative.postprocess]]
name = 'rename'

[datasets.era5_cumulative.postprocess.name_dict]
surface_solar_radiation_downwards = 'ssrd'
surface_thermal_radiation_downwards = 'strd'
total_precipitation = 'tp'

[[datasets.era5_cumulative.postprocess]]
name = 'rename_coordinates'
name_dict = {latitude = 'lat', longitude = 'lon'}

# ==== GLOFAS SECTION ====

[datasets.glofas.checkpointing]
step = '128D'
compressor = {cname = 'lz4', clevel = 3}

[[datasets.glofas.parts]]
filename_or_obj = 'ewds://cems-glofas-historical'
engine = 'earlywarningdatastore'
system_version = 'version_4_0'
hydrological_model = 'lisflood'
product_type = 'consolidated'
variable = 'river_discharge_in_the_last_24_hours'
chunks = {time = 1, latitude = -1, longitude = -1}

[[datasets.glofas.postprocess]]
name = 'regrid'
method = 'conservative'
latitude_dim = 'latitude'
longitude_dim = 'longitude'
kwargs = {skipna = true, nan_threshold = 0.0}
grid = {south = 30.00, north = 46.00, west = -5.60, east = 36.40, resolution_lat = 0.04, resolution_lon = 0.04}

[[datasets.glofas.postprocess]]
name = 'astype'
casting = 'same_kind'
dtype = 'float32'

[[datasets.glofas.postprocess]]
name = 'rename_coordinates'
name_dict = {latitude = 'lat', longitude = 'lon'}

[[datasets.glofas_mask.parts]]
filename_or_obj = 'https://confluence.ecmwf.int/download/attachments/242067380/uparea_glofas_v4_0.nc'
engine = 'netcdfoverhttp'
chunks = {latitude = -1, longitude = -1}

[[datasets.glofas_mask.postprocess]]
name = 'regrid'
method = 'conservative'
latitude_dim = 'latitude'
longitude_dim = 'longitude'
kwargs = {skipna = true, nan_threshold = 0.0}
grid = {south = 30.00, north = 46.00, west = -5.60, east = 36.40, resolution_lat = 0.04, resolution_lon = 0.04}

[[datasets.glofas_mask.postprocess]]
name = 'astype'
uparea = {dtype = 'float32', casting='same_kind'}

[[datasets.glofas_mask.postprocess]]
name = 'get_notnull_mask'
variable = 'uparea'
mask_name = 'glofas_mask'

[[datasets.glofas_mask.postprocess]]
name = 'rename_coordinates'
name_dict = {latitude = 'lat', longitude = 'lon'}

# ==== MEDSEA PHYS SECTION ====

[datasets.medsea_phys.checkpointing]
step = '1D'
compressor = {cname = 'lz4', clevel = 3}

[[datasets.medsea_phys.parts]]
filename_or_obj = 'cm://cmems_mod_med_phy-cur_my_4.2km_P1D-m'
engine = 'copernicusmarine'
dataset_version = '202511'
variables = ['uo', 'vo']
dataset_part = 'default'
service = 'arco-geo-series'
chunks = {time = 1, depth = 1, latitude = -1, longitude = -1}

[[datasets.medsea_phys.parts]]
filename_or_obj = 'cm://cmems_mod_med_phy-sal_my_4.2km_P1D-m'
engine = 'copernicusmarine'
dataset_version = '202511'
variables = ['so']
dataset_part = 'default'
service = 'arco-geo-series'
chunks = {time = 1, depth = 1, latitude = -1, longitude = -1}

[[datasets.medsea_phys.parts]]
filename_or_obj = 'cm://cmems_mod_med_phy-temp_my_4.2km_P1D-m'
engine = 'copernicusmarine'
dataset_version = '202511'
variables = ['thetao', 'bottomT']
dataset_part = 'default'
service = 'arco-geo-series'
chunks = {time = 1, depth = 1, latitude = -1, longitude = -1}

[[datasets.medsea_phys.parts]]
filename_or_obj = 'cm://cmems_mod_med_phy-ssh_my_4.2km_P1D-m'
engine = 'copernicusmarine'
dataset_version = '202511'
variables = ['zos']
dataset_part = 'default'
service = 'arco-geo-series'
chunks = {time = 1, latitude = -1, longitude = -1}

[[datasets.medsea_phys.parts]]
filename_or_obj = 'cm://cmems_mod_med_phy-mld_my_4.2km_P1D-m'
engine = 'copernicusmarine'
dataset_version = '202511'
variables = ['mlotst']
dataset_part = 'default'
service = 'arco-geo-series'
chunks = {time = 1, latitude = -1, longitude = -1}

[[datasets.medsea_phys.postprocess]]
name = 'isel'
depth = {start = 0, stop = 125}

[[datasets.medsea_phys.postprocess]]
name = 'fillna'
value = 0.0

[[datasets.medsea_phys.postprocess]]
name = 'regrid'
method = 'cubic'
latitude_dim = 'latitude'
longitude_dim = 'longitude'
grid = {south = 30.00, north = 46.00, west = -5.60, east = 36.40, resolution_lat = 0.04, resolution_lon = 0.04}

[[datasets.medsea_phys.postprocess]]
name = 'astype'
casting = 'same_kind'
dtype = 'float32'

[[datasets.medsea_phys.postprocess]]
name = 'rename_coordinates'
name_dict = {latitude = 'lat', longitude = 'lon', depth = 'level'}
set_new_coordinate = {'level' = 'auto'}

[[datasets.medsea_phys_mask.parts]]
filename_or_obj = 'cm://cmems_mod_med_phy_my_4.2km_static'
engine = 'copernicusmarine'
dataset_version = '202211'
variables = ['deptho', 'depth']
dataset_part = 'bathy'
service = 'static-arco'
chunks = {depth = 1, latitude = -1, longitude = -1}

[[datasets.medsea_phys_mask.postprocess]]
name = 'regrid'
method = 'conservative'
latitude_dim = 'latitude'
longitude_dim = 'longitude'
kwargs = {skipna = false, output_chunks = {depth = 1, latitude = -1, longitude = -1}}
grid = {south = 30.00, north = 46.00, west = -5.60, east = 36.40, resolution_lat = 0.04, resolution_lon = 0.04}

[[datasets.medsea_phys_mask.postprocess]]
name = 'astype'
dtype = 'float32'
casting = 'same_kind'

[[datasets.medsea_phys_mask.postprocess]]
name = 'rename'
name_dict = {deptho = 'medsea_phys_deptho'}

[[datasets.medsea_phys_mask.postprocess]]
name = 'get_sea_mask'
bathymetry = 'medsea_phys_deptho'
depth_coordinate = 'depth'
depth_dim = 'depth'
mask_name = 'medsea_phys_mask'

[[datasets.medsea_phys_mask.postprocess]]
name = 'isel'
depth = {start = 0, stop = 125}

[[datasets.medsea_phys_mask.postprocess]]
name = 'rename_coordinates'
name_dict = {latitude = 'lat', longitude = 'lon', depth = 'level'}
set_new_coordinate = {'level' = 'auto'}

# ==== MEDSEA WAVE SECTION ====

[datasets.medsea_wave.checkpointing]
step = '128D'
compressor = {cname = 'lz4', clevel = 3}

[[datasets.medsea_wave.parts]]
filename_or_obj = 'cm://cmems_mod_med_wav_my_4.2km_PT1H-i'
engine = 'copernicusmarine'
dataset_version = '202511'
variables = ['VHM0', 'VTM10', 'VMDR', 'VSDX', 'VSDY']
dataset_part = 'default'
service = 'arco-geo-series'
chunks = {time = 24, latitude = -1, longitude = -1}

[[datasets.medsea_wave.postprocess]]
name = 'fillna'
value = 0.0

[[datasets.medsea_wave.postprocess]]
name = 'regrid'
method = 'cubic'
latitude_dim = 'latitude'
longitude_dim = 'longitude'
grid = {south = 30.00, north = 46.00, west = -5.60, east = 36.40, resolution_lat = 0.04, resolution_lon = 0.04}

[[datasets.medsea_wave.postprocess]]
name = 'resample'
time = '1 D'
label = 'left'
closed = 'left'
reduce = 'mean'

[[datasets.medsea_wave.postprocess]]
name = 'astype'
casting = 'same_kind'
dtype = 'float32'

[[datasets.medsea_wave.postprocess]]
name = 'rename'
name_dict = {VHM0 = 'swh', VTM10 = 'mwp', VSDX = 'usd', VSDY = 'vsd', VMDR = 'mwd'}

[[datasets.medsea_wave.postprocess]]
name = 'rename_coordinates'
name_dict = {latitude = 'lat', longitude = 'lon'}

[[datasets.medsea_wave_mask.parts]]
filename_or_obj = 'cm://cmems_mod_med_wav_my_4.2km_static'
engine = 'copernicusmarine'
dataset_version = '202211'
variables = ['deptho']
dataset_part = 'bathy'
service = 'static-arco'
chunks = {latitude = -1, longitude = -1}

[[datasets.medsea_wave_mask.postprocess]]
name = 'regrid'
method = 'conservative'
latitude_dim = 'latitude'
longitude_dim = 'longitude'
kwargs = {skipna = false, output_chunks = {latitude = -1, longitude = -1}}
grid = {south = 30.00, north = 46.00, west = -5.60, east = 36.40, resolution_lat = 0.04, resolution_lon = 0.04}

[[datasets.medsea_wave_mask.postprocess]]
name = 'astype'
dtype = 'float32'
casting = 'same_kind'

[[datasets.medsea_wave_mask.postprocess]]
name = 'is_positive_mask'
variable = 'deptho'
mask_name = 'medsea_wave_mask'

[[datasets.medsea_wave_mask.postprocess]]
name = 'rename'
name_dict = {deptho = 'medsea_wave_deptho'}

[[datasets.medsea_wave_mask.postprocess]]
name = 'rename_coordinates'
name_dict = {latitude = 'lat', longitude = 'lon'}

# ==== MEDSEA BIO SECTION ====

[datasets.medsea_bio.checkpointing]
step = '2D'
compressor = {cname = 'lz4', clevel = 3}

[[datasets.medsea_bio.parts]]
filename_or_obj = 'cm://cmems_mod_med_bgc-car_my_4.2km_P1D-m'
engine = 'copernicusmarine'
dataset_version = '202511'
variables = ['ph', 'dissic', 'talk']
dataset_part = 'default'
service = 'arco-geo-series'
chunks = {time = 1, depth = 1, latitude = -1, longitude = -1}

[[datasets.medsea_bio.parts]]
filename_or_obj = 'cm://cmems_mod_med_bgc-co2_my_4.2km_P1D-m'
engine = 'copernicusmarine'
dataset_version = '202511'
variables = ['spco2', 'fpco2']
dataset_part = 'default'
service = 'arco-geo-series'
chunks = {time = 1, latitude = -1, longitude = -1}

[[datasets.medsea_bio.parts]]
filename_or_obj = 'cm://cmems_mod_med_bgc-nut_my_4.2km_P1D-m'
engine = 'copernicusmarine'
dataset_version = '202511'
variables = ['no3', 'po4', 'nh4']
dataset_part = 'default'
service = 'arco-geo-series'
chunks = {time = 1, depth = 1, latitude = -1, longitude = -1}

[[datasets.medsea_bio.parts]]
filename_or_obj = 'cm://cmems_mod_med_bgc-plankton_my_4.2km_P1D-m'
engine = 'copernicusmarine'
dataset_version = '202511'
variables = ['phyc', 'chl']
dataset_part = 'default'
service = 'arco-geo-series'
chunks = {time = 1, depth = 1, latitude = -1, longitude = -1}

[[datasets.medsea_bio.parts]]
filename_or_obj = 'cm://cmems_mod_med_bgc-bio_my_4.2km_P1D-m'
engine = 'copernicusmarine'
dataset_version = '202511'
variables = ['nppv', 'o2']
dataset_part = 'default'
service = 'arco-geo-series'
chunks = {time = 1, depth = 1, latitude = -1, longitude = -1}

[[datasets.medsea_bio.postprocess]]
name = 'fillna'
value = 0.0

[[datasets.medsea_bio.postprocess]]
name = 'regrid'
method = 'cubic'
latitude_dim = 'latitude'
longitude_dim = 'longitude'
grid = {south = 30.00, north = 46.00, west = -5.60, east = 36.40, resolution_lat = 0.04, resolution_lon = 0.04}

[[datasets.medsea_bio.postprocess]]
name = 'astype'
casting = 'same_kind'
dtype = 'float32'

[[datasets.medsea_bio.postprocess]]
name = 'rename_coordinates'
name_dict = {latitude = 'lat', longitude = 'lon', depth = 'level'}
set_new_coordinate = {'level' = 'auto'}

[[datasets.medsea_bio_mask.parts]]
filename_or_obj = 'cm://cmems_mod_med_bgc_my_4.2km_static'
engine = 'copernicusmarine'
dataset_version = '202211'
variables = ['deptho', 'depth']
dataset_part = 'bathy'
service = 'static-arco'
chunks = {depth = 1, latitude = -1, longitude = -1}

[[datasets.medsea_bio_mask.postprocess]]
name = 'regrid'
method = 'conservative'
latitude_dim = 'latitude'
longitude_dim = 'longitude'
kwargs = {skipna = false, output_chunks = {depth = 1, latitude = -1, longitude = -1}}
grid = {south = 30.00, north = 46.00, west = -5.60, east = 36.40, resolution_lat = 0.04, resolution_lon = 0.04}

[[datasets.medsea_bio_mask.postprocess]]
name = 'astype'
dtype = 'float32'
casting = 'same_kind'

[[datasets.medsea_bio_mask.postprocess]]
name = 'get_sea_mask'
bathymetry = 'deptho'
depth_coordinate = 'depth'
depth_dim = 'depth'
mask_name = 'medsea_bio_mask'

[[datasets.medsea_bio_mask.postprocess]]
name = 'rename_coordinates'
name_dict = {latitude = 'lat', longitude = 'lon', depth = 'level'}
set_new_coordinate = {'level' = 'auto'}

[[datasets.medsea_bio_mask.postprocess]]
name = 'rename'
name_dict = {deptho = 'medsea_bio_deptho'}

[[postprocess]]
name = 'transpose'
dims = ['time', 'level', 'lat', 'lon']

[save]
consolidated = true
chunk = {time = 1, level = -1, lat = -1, lon = -1}
compressor = {cname = 'lz4', clevel = 1}

[checks.valid_time_coordinate]
freq = '1D'

[checks.ensure_no_nans]
glofas_mask = ['dis24', 'uparea']
medsea_phys_mask = ['uo', 'vo', 'so', 'thetao', 'bottomT', 'zos', 'mlotst', 'medsea_phys_deptho']
medsea_wave_mask = ['swh', 'mwp', 'mwd', 'usd', 'vsd', 'medsea_wave_deptho']
medsea_bio_mask = ['ph', 'dissic', 'talk', 'spco2', 'fpco2', 'no3', 'po4', 'nh4', 'phyc', 'chl', 'nppv', 'o2', 'medsea_bio_deptho']

